name: Yaml lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-for-typos:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    name: yaml-lint
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ibiqlik/action-yamllint@b2aeacc1b7eeb8c23e84bba320d04fb5d6a323ee # v3.0.0
        with:
          config_file: .yamllint.yaml
